"""empty message

Revision ID: 32211dcdd282
Revises: 18f75f52bef9
Create Date: 2021-09-28 11:47:03.457343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32211dcdd282'
down_revision = '18f75f52bef9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statistics', 'author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statistics', sa.Column('author', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
