"""make user non-unique on covid post table

Revision ID: 5a23716d7af5
Revises: a83500fe0b44
Create Date: 2021-09-29 21:22:35.691794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a23716d7af5'
down_revision = 'a83500fe0b44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('covid_user_id_key', 'covid', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('covid_user_id_key', 'covid', ['user_id'])
    # ### end Alembic commands ###
