"""empty message

Revision ID: 795916c0df9d
Revises: d077e354f623
Create Date: 2021-09-29 08:00:02.764301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '795916c0df9d'
down_revision = 'd077e354f623'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
