"""empty message

Revision ID: b37b5e1b3312
Revises: 0f69776696fe
Create Date: 2021-09-29 09:06:39.719680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b37b5e1b3312'
down_revision = '0f69776696fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comments_covid_id_fkey', 'comments', type_='foreignkey')
    op.drop_column('comments', 'covid_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('covid_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('comments_covid_id_fkey', 'comments', 'covid', ['covid_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
