"""empty message

Revision ID: d077e354f623
Revises: 7270abeae03c
Create Date: 2021-09-28 23:27:58.287197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd077e354f623'
down_revision = '7270abeae03c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comments_covid_id_fkey', 'comments', type_='foreignkey')
    op.drop_column('comments', 'covid_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('covid_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('comments_covid_id_fkey', 'comments', 'statistics', ['covid_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
